# Arange

In [1]:
import numpy as np

In [3]:
np.arange(1, 10,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3.0)

array([0., 1., 2.])

In [5]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(20, dtype="complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [8]:
np.arange(1, 10, 2, dtype="float")

array([1., 3., 5., 7., 9.])

# Zeros()

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3, 4), order='F')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Ones

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(7, dtype='int')

array([1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones([3, 4], order='F')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# empty

In [16]:
import numpy as np
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.empty([3, 4], dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Linspace

In [18]:
np.linspace(1, 100, num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
np.linspace(1, 100, num=5, endpoint=False)

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [20]:
np.linspace(1, 100, num=5, retstep=True)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

In [21]:
np.linspace(1, 100, num=4, dtype=int)

array([  1,  34,  67, 100])

In [22]:
np.linspace(2, 20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

# Eye

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [25]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# identity function

In [28]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Random 

In [3]:
# rand()
# randn()
# randf()
# randint()
### rand()
np.random.rand(5,)

array([0.31751438, 0.31912465, 0.90746833, 0.78885664, 0.0769015 ])

In [30]:
np.random.rand(2, 3)

array([[0.59408745, 0.14407386, 0.30442664],
       [0.95264589, 0.68650312, 0.05346448]])

In [31]:
### randn
np.random.randn(5)

array([ 1.53508394,  0.98390364, -0.55875866, -0.35864458,  0.67602102])

In [32]:
np.random.random_sample((2, 3))

array([[0.9318579 , 0.03769721, 0.59388416],
       [0.79803281, 0.70670076, 0.9731881 ]])

In [8]:
np.random.randint(3, size=10)

array([2, 1, 0, 2, 2, 0, 0, 0, 0, 0])

In [34]:
np.random.randint(3, size=5)

array([1, 1, 1, 2, 0])

In [35]:
np.random.randint(3, size=(4, 5))

array([[0, 2, 0, 2, 1],
       [2, 2, 2, 1, 2],
       [2, 2, 1, 0, 1],
       [2, 2, 1, 0, 1]])

# Attributes of Array

In [36]:
# Dimension
# shape
# size
# dtype
# itemsize
a = np.array([1, 2, 3, 4, 5])
a.ndim

1

In [37]:
b = np.array([[1, 2],[3, 4]])
b.ndim

2

In [38]:
# shape
a = np.zeros(5)
a.shape

(5,)

In [39]:
b = np.array([[1, 2],[3, 4]])
b.shape

(2, 2)

In [41]:
c = np.zeros((2, 3, 4))

In [42]:
c.shape

(2, 3, 4)

In [43]:
c.dtype

dtype('float64')

In [44]:
c.size

24

In [45]:
c.itemsize

8

# Data types in numpy

In [46]:
"""
Numerical Data types
      1. Boolean
      2. Integer
      3. Unsigned
      4. Float
      5. Complex

"""
a = np.zeros(5)
a.dtype

dtype('float64')

In [47]:
b = np.zeros(6, dtype=np.int8)
b.dtype

dtype('int8')

In [48]:
x = np.float32(1)

In [49]:
x

1.0

In [50]:
x.dtype

dtype('float32')

In [51]:
a = np.array([1, 2, 3, 44, 5], dtype='f')
a.dtype

dtype('float32')

In [52]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [53]:
a.astype(int)

array([0, 0, 0])

In [54]:
np.float64(a)

array([0., 0., 0.])

In [55]:
a.dtype

dtype('float64')

# INDEXING 

In [56]:
# id array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [57]:
a[3]

4

In [58]:
a[-2]

4

In [59]:
a[0]

1

In [60]:
# 2d array
b = np.array([[1, 2],[3, 4]])
b[0][1]


2

In [61]:
b[-2][-2]

1

In [62]:
b[0]

array([1, 2])

In [66]:
c = [[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],[[13, 14, 15, 16],[17, 18, 19, 20], [21, 22, 23, 24]]]
d = np.array(c)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [67]:
d[0][0][1]

2

In [68]:
d[-2][-3][-3]

2

In [69]:
d[1][0][3]

16

# SLICING

In [70]:
# 1d array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a[2:5]

array([3, 4, 5])

In [71]:
# 2d array
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
b[1:,1:]

array([[4],
       [6]])

In [75]:
b[1:,:1]

array([[3],
       [5]])

In [76]:
#3d array
c = [[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],[[13, 14, 15, 16],[17, 18, 19, 20], [21, 22, 23, 24]]]
d = np.array(c)
d[:, :, :1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [78]:
d[:, 1:, ::2]

array([[[ 5,  7],
        [ 9, 11]],

       [[17, 19],
        [21, 23]]])

# Advanced Indexing

In [79]:
# 1d array
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
index = np.array([1, 4, 5])
a[index]

array([2, 5, 6])

In [83]:
a[[1, 2, 3, 4]]

array([2, 3, 4, 5])

In [86]:
# 2d array
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
b[[0, 2],[2, 0]]

array([3, 7])

In [91]:
b[[0, 2],[2, 0]]

array([3, 7])

In [94]:
b[[1, 2, 1],[0, 1, 2]]


array([4, 8, 6])

In [95]:
c = np.arange(1, 10)

In [96]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
c[[1, 4, 1, 4]]

array([2, 5, 2, 5])

In [98]:
# Boolian indexing
a = np.array([[1, -2, 3],[4, -2, 3]])
a

array([[ 1, -2,  3],
       [ 4, -2,  3]])

In [99]:
a[a<0]

array([-2, -2])

In [100]:
a[a>0]

array([1, 3, 4, 3])

In [101]:
a[a>2]*2

array([6, 8, 6])

# Arithmatic operation in numpy

In [102]:
# using scalars
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [103]:
a+2

array([3, 4, 5, 6])

In [104]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [105]:
a*3

array([ 3,  6,  9, 12])

In [106]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [107]:
a-1

array([0, 1, 2, 3])

In [108]:
a**2


array([ 1,  4,  9, 16], dtype=int32)

In [109]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [110]:
# arithmatic operation on 2 arrays
# same shaped arrays
# 1d array
a = np.arange(1, 5)
b = np.array([10, 20, 30, 40])
a+b

array([11, 22, 33, 44])

In [111]:
a*b

array([ 10,  40,  90, 160])

In [112]:
a/b

array([0.1, 0.1, 0.1, 0.1])

In [113]:
a-b

array([ -9, -18, -27, -36])

In [5]:
# 2d array
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
b = np.array([[1, 2, 1],[2, 1, 1]])
print(b)
a

[[1 2 3]
 [4 5 6]]
[[1 2 1]
 [2 1 1]]


array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
b

array([[1, 2, 1],
       [2, 1, 1]])

In [123]:
a+b


array([[2, 4, 4],
       [6, 6, 7]])

In [124]:
a*b

array([[1, 4, 3],
       [8, 5, 6]])

# Broadcasting

In [ ]:
"""
# Rules:
    # main Rule:
        1. size of each dimension should be same.
        2. size of one of the dimension should be 1.
    # some other rules:
        RULE1: if the two arrays differ in their number of dimensions, the shape of the one with fewer dimension 
               is padded with ones on its leading side(left side).
        RULE2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in
               that dimension is stretched to match the other shape.
        RUlE3: If in any dimension the sizes disagree and neither eequal to1, an error is raised.
"""

# Reshaping Array

In [131]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
a.shape

(10,)

In [133]:
b = np.reshape(a, (5, 2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
b.shape

(5, 2)

In [128]:
c = np.reshape(a, (5, 2), order='F')

In [129]:
c

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [134]:
a.size

10

In [136]:
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# resize

In [138]:
a = np.arange(5)
np.resize(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 0]])

In [139]:
np.resize(a, (5, 5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [140]:
a.resize((5, 2))

In [141]:
a

array([[0, 1],
       [2, 3],
       [4, 0],
       [0, 0],
       [0, 0]])

# Flatten & Ravel

In [ ]:
"""
FLATTEN: 
    1.returns copy of the array
    2. method of nd array object
    3. syntax = array.flatten(order='F')
RAVEL: 
    1. returns copy only if it is needed, otherwise it will give view of the data
    2.library level function
    3. syntax = 1. np.ravel(array, order='F') or 2. array.ravel(order='F')
"""

In [8]:
b = np.array([[[1, 2, 3],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
print(b)
print(b.ndim)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [9]:
b.flatten(order='C')

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
b.flatten(order="F")

array([ 1,  6,  3,  9,  2,  7,  4, 10,  3,  8,  5, 11])

In [151]:
b

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [152]:
b.flatten(order="k")

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [153]:
b.flatten(order='A')

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [149]:
a.flatten()

array([1, 2, 3, 4])

In [150]:
a.flatten(order='F')

array([1, 3, 2, 4])

# Ravel

In [154]:
a = np.array([[10, 20],[30, 40]])
a

array([[10, 20],
       [30, 40]])

In [12]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [157]:
np.ravel(a, order='F')

array([10, 30, 20, 40])

In [158]:
b = np.array([[[1, 2, 3],[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
b

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [159]:
np.ravel(b)

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
b.ravel(order='F')

array([ 1,  6,  3,  9,  2,  7,  4, 10,  3,  8,  5, 11])

# Transpose function

In [162]:
array1 = np.arange(1, 11).reshape(5, 2)
array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [163]:
np.transpose(array1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [164]:
# 3d arraya
a = np.arange(1, 25).reshape(2, 3, 4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [165]:
a.shape

(2, 3, 4)

In [166]:
np.transpose(a)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [167]:
np.transpose(a).shape

(4, 3, 2)

In [168]:
array1 = np.arange(1, 11).reshape(5, 2)
array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [169]:
np.transpose(array1, axes=(1, 0))

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [170]:
np.transpose(array1, axes=(0, 1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [171]:
# 3d array
a = np.arange(1, 25).reshape(2, 3, 4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [172]:
np.transpose(a, axes=(1, 2, 0))

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [174]:
a.transpose()

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [175]:
a.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

# Swapaxes

In [17]:
a = np.arange(1, 25).reshape(2, 3, 4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
a.ndim

3

In [18]:
np.swapaxes(a, 1, 2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [179]:
a.swapaxes(1, 2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

# Split and join numpy array

In [183]:
a = np.arange(1, 5)
b = np.arange(6)
np.concatenate((a, b))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [185]:
c = np.zeros(10)
np.concatenate((a,b), out=c)

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [186]:
c

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [20]:
# vstack
a = np.arange(6)
n = np.arange(5)
c = np.arange(5)
np.vstack((c,n))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [188]:
np.vstack((n,c))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [189]:
# hstack
np.hstack((a,n))

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4])

In [ ]:
# split array  # hsplit # vsplit


# insert

In [192]:
# numpy.insert(array, obj, values, axis=None)
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.insert(a, 1, 45.65)

array([ 0, 45,  1,  2,  3,  4,  5])

In [194]:
np.insert(a, (1, 3, ), 45)

array([ 1, 45,  2,  3, 45,  4,  5,  6,  7,  8,  9, 10])

In [195]:
#2d array
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [196]:
np.insert(a, 1, 23) # it wil flatten to 1 d array and give out

array([ 1, 23,  2,  3,  4])

In [197]:
np.insert(a, 1, 23, axis=0)

array([[ 1,  2],
       [23, 23],
       [ 3,  4]])

In [198]:
np.insert(a, 1, 23, axis=1)

array([[ 1, 23,  2],
       [ 3, 23,  4]])

In [199]:
np.insert(a,1, [1, 2], axis=0)

array([[1, 2],
       [1, 2],
       [3, 4]])

In [200]:
np.insert(a,1, [1, 2], axis=1)

array([[1, 1, 2],
       [3, 2, 4]])

# append

In [201]:
# numpy.append(array, values, axis=None)
np.append(a, 3452)

array([   1,    2,    3,    4, 3452])

In [202]:
np.append(a, [[3, 4]], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [203]:
np.append(a, [[3, 4]], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [204]:
np.append(a, [[3], [4]], axis=1)

array([[1, 2, 3],
       [3, 4, 4]])

In [205]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

# Delete function

In [206]:
# numpy.delete(array, obj, axis=None)
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [207]:
np.delete(a, 2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [208]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [209]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [210]:
np.delete(a, 2)

array([1, 2, 4])

In [213]:
np.delete(a, 1, axis=0)

array([[1, 2]])

In [214]:
np.delete(a, 1, axis=1)

array([[1],
       [3]])

# MATRIX

In [215]:
a = np.array([[1,2],[3,4]])
b = np.array([[10, 20],[30, 40]])
a+b

array([[11, 22],
       [33, 44]])

In [216]:
a.dot(b)

array([[ 70, 100],
       [150, 220]])

In [217]:
# matrix library
# numpy.matrix(data, dtype=none, copy=true)
a = np.matrix("1 2; 3 4")
a

matrix([[1, 2],
        [3, 4]])

In [218]:
b = np.matrix([[10, 20],[30, 40]])
b

matrix([[10, 20],
        [30, 40]])

In [219]:
a+b

matrix([[11, 22],
        [33, 44]])

In [220]:
a*b

matrix([[ 70, 100],
        [150, 220]])

# linear algebra

In [221]:
# numpy.linalg()
"""
1. Invert the matrix....numpy.linalg.inv()
2. power of matrix
3. linear equation
4. Determinants
"""
a = np.array([[1, 2],[3, 4]])
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [222]:
np.allclose(np.dot(a, b), np.eye(2))

True

In [223]:
np.dot(a,b)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# matrix power

In [225]:
# numpy.linalg.matrix_power(a, n)
a = np.array([[1, 2],[3, 4]])
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

# Linear Equation

In [226]:
# numpy.linalg.solve(a, b)
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])
np.linalg.solve(a,b)

array([2., 3.])

In [227]:
a = np.array([[6, 2, -5], [3, 3, -2], [7, 5, -3]])
b = np.array([13, 13, 26])

In [228]:
np.linalg.solve(a, b)

array([2., 3., 1.])

# Determinant of a matrix

In [229]:
a = np.array([[3, 1],[1, 2]])
np.linalg.det(a)

5.000000000000001

In [233]:
round(np.linalg.det(a))

5

In [235]:
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
np.linalg.det(b)

6.66133814775094e-16

In [238]:
round(np.linalg.det(b))

0